// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe6ar9eCgwwbRGs3k5Icm8PZfAxcPTinU',
    appId: '1:394742476706:web:b6dcc03b7500dc08070cfb',
    messagingSenderId: '394742476706',
    projectId: 'arcane-forge-dev',
    authDomain: 'arcane-forge-dev.firebaseapp.com',
    storageBucket: 'arcane-forge-dev.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-r_htIkc1HOI-1S-k0WAtTEojeF81C8o',
    appId: '1:298642052974:ios:d8dc3fb8c2bf3168b2937f',
    messagingSenderId: '298642052974',
    projectId: 'arcane-forge-dev-a5d91',
    storageBucket: 'arcane-forge-dev-a5d91.firebasestorage.app',
    iosBundleId: 'ai.arcaneforge.arcaneForge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSIk76XEV_aI2hawxH5YgE18U26TnjYz0',
    appId: '1:298642052974:web:85e92fcb85b70583b2937f',
    messagingSenderId: '298642052974',
    projectId: 'arcane-forge-dev-a5d91',
    authDomain: 'arcane-forge-dev-a5d91.firebaseapp.com',
    storageBucket: 'arcane-forge-dev-a5d91.firebasestorage.app',
    measurementId: 'G-QMYWWCE19M',
  );
}